export const orderConstants = {
    ADD_REQUEST: 'ORDER_ADD_REQUEST',
    ADD_SUCCESS: 'ORDER_ADD_SUCCESS',
    ADD_FAILURE: 'ORDER_ADD_FAILURE',

    UPDATE_REQUEST: 'ORDER_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'ORDER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'ORDER_UPDATE_FAILURE',

    DELETE_REQUEST: 'ORDER_DELETE_REQUEST',
    DELETE_SUCCESS: 'ORDER_DELETE_SUCCESS',
    DELETE_FAILURE: 'ORDER_DELETE_FAILURE',  
}