export const productConstants = {

    GETALL_REQUEST: 'PRODUCTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PRODUCTS_GETALL_FAILURE',

    GET_REQUEST: 'PRODUCTS_GET_REQUEST',
    GET_SUCCESS: 'PRODUCTS_GET_SUCCESS',
    GET_FAILURE: 'PRODUCTS_GET_FAILURE',
};